spring.application.name=REVIEWS-SERVICE
server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/reviewsdb
spring.datasource.username=postgres
spring.datasource.password=slk@SOFT123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ? FIX
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=false